version: '3.9'

volumes:
  ckieDev: {}

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5431:5432
    volumes:
      - ckieDev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ckie
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ckie